name: Testes Playwright

on:
  push:
    branches: [ main ]    # Rode quando fizer push para main
  pull_request:
    branches: [ main ]    # E também para PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Chromium apenas
        run: 
          playwright install chromium

      - name: Rodar testes com Pytest
        run: pytest -v
